//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Soyokaze.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SOYOKAZE_DIALOG             102
#define ID_STRING_MISMATCH              102
#define ID_STRING_DEFAULTDESCRIPTION    103
#define IDS_MENUTEXT_SHOW               104
#define IDC_POINTER                     104
#define IDS_ERR_NAMEISEMPTY             105
#define IDS_ERR_ILLEGALCHARCONTAINS     106
#define IDC_CAPTUREWINDOW               106
#define IDS_ERR_NAMEALREADYEXISTS       107
#define IDS_ERR_PATHISEMPTY             108
#define IDS_ERR_PATH0ISEMPTY            109
#define IDS_NAME                        110
#define IDS_DESCRIPTION                 111
#define IDS_CONFIRM_DELETE              112
#define IDS_ERR_NAMEDOESNOTEXIST        113
#define IDS_FILTER_EXE                  114
#define IDS_ERR_HOTKEYALREADYUSE        115
#define IDS_ERR_HELPDOESNOTEXIST        116
#define IDS_CONFIRM_DELETESHORTCUT      117
#define IDS_MENUTEXT_HIDE               118
#define IDS_CONFIRM_DELETESHORTCUT2     119
#define IDS_ERR_GETNEXTWINDOW           119
#define IDS_ERR_QUERYPROCESSINFO        120
#define IDS_NEWREGISTER                 121
#define IDS_PASTE                       122
#define IDS_BUILDDATE                   123
#define IDS_VERSION                     124
#define IDR_MAINFRAME                   128
#define IDI_ICON2                       131
#define IDI_ICON1                       136
#define IDD_SETTING                     137
#define IDD_NEWCOMMAND                  140
#define IDD_KEYWORDMANAGER              143
#define IDD_HOTKEY                      146
#define IDD_SHORTCUT                    149
#define IDD_REGISTER_ITEMS              151
#define IDD_BASICSETTING                153
#define IDD_EXTENSIONSETTING            156
#define IDD_SHORTCUTSETTING             158
#define IDC_EDIT_COMMAND                1000
#define IDC_STATIC_DESCRIPTION          1001
#define IDC_STATIC_VERSION              1002
#define IDC_EDIT_COMMAND2               1002
#define IDC_STATIC_BUILDDATE            1003
#define IDC_LIST_CANDIDATE              1004
#define IDC_STATIC_ICON                 1005
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_DESCRIPTION            1008
#define IDC_CHECK_RUNASADMIN            1009
#define IDC_CHECK_USE0                  1010
#define IDC_BUTTON_BROWSEFILE1          1011
#define IDC_BUTTON_BROWSEDIR1           1012
#define IDC_BUTTON_BROWSEFILE2          1013
#define IDC_BUTTON_BROWSEDIR2           1014
#define IDC_STATIC_PATH                 1015
#define IDC_STATIC_PARAM                1016
#define IDC_STATIC_PATH0                1017
#define IDC_STATIC_PARAM00              1018
#define IDC_EDIT_PATH                   1019
#define IDC_EDIT_PARAM                  1020
#define IDC_EDIT_HOTKEY                 1020
#define IDC_EDIT_PATH0                  1021
#define IDC_EDIT_PARAM0                 1022
#define IDC_EDIT_DIR                    1023
#define IDC_BUTTON_BROWSEDIR3           1024
#define IDC_COMBO_SHOWTYPE              1025
#define IDC_STATIC_STATUSMSG            1026
#define IDC_STATIC_PARAM0               1027
#define IDC_STATIC_NAME                 1028
#define IDC_LIST_COMMANDS               1029
#define IDC_BUTTON_NEW                  1030
#define IDC_BUTTON_EDIT                 1031
#define IDC_COMBO_MATCHLEVEL            1031
#define IDC_BUTTON_DELETE               1032
#define IDC_CHECK_USEFILER              1032
#define IDC_CHECK_TOPMOST               1033
#define IDC_COMBO_TRANSPARENCY          1034
#define IDC_EDIT_ALPHA                  1035
#define IDC_BUTTON_BROWSEFILE           1036
#define IDC_EDIT_FILERPARAM             1037
#define IDC_BUTTON_HOTKEY               1038
#define IDC_EDIT_FILERPATH              1039
#define IDC_CHECK_SHIFT                 1040
#define IDC_CHECK_USEFILER2             1040
#define IDC_CHECK_SHOWTOGGLE            1040
#define IDC_CHECK_ALT                   1041
#define IDC_CHECK_CTRL                  1042
#define IDC_CHECK_WIN                   1043
#define IDC_COMBO_VK                    1044
#define IDC_SYSLINK1                    1045
#define IDC_BUTTON_SHORTCUT             1046
#define IDC_SYSLINK2                    1046
#define IDC_CHECK_SENDTO                1047
#define IDC_SYSLINK3                    1047
#define IDC_STATIC_REMARK               1048
#define IDC_CHECK_STARTMENU             1049
#define IDC_CHECK_DESKTOP               1050
#define IDC_CHECK_STARTUP               1051
#define IDC_LIST_FILES                  1054
#define IDC_CHECK_RESOLVELINKS          1055
#define IDC_TREE_PAGES                  1056
#define IDC_STATIC_BREADCRUMBS          1057
#define IDC_STATIC_PAGEAREA             1058
#define ID_A                            32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
