//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Soyokaze.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SOYOKAZE_DIALOG             102
#define IDS_ERR_GROUPITEMEMPTY          102
#define ID_STRING_MISMATCH              103
#define ID_STRING_DEFAULTDESCRIPTION    104
#define IDS_MENUTEXT_SHOW               105
#define IDC_POINTER                     106
#define IDS_TITLE_CONFIRMRUNGROUP       106
#define IDS_ERR_NAMEISEMPTY             107
#define IDS_ERR_ILLEGALCHARCONTAINS     108
#define IDC_CAPTUREWINDOW               109
#define IDS_CONFIRMRUNGROUP             109
#define IDS_ERR_NAMEALREADYEXISTS       110
#define IDS_ERR_PATHISEMPTY             111
#define IDS_ERR_PATH0ISEMPTY            112
#define IDS_NAME                        113
#define IDS_DESCRIPTION                 114
#define IDS_CONFIRM_DELETE              115
#define IDS_ERR_NAMEDOESNOTEXIST        116
#define IDS_FILTER_EXE                  117
#define IDS_ERR_HOTKEYALREADYUSE        118
#define IDS_ERR_HELPDOESNOTEXIST        119
#define IDS_CONFIRM_DELETESHORTCUT      120
#define IDS_MENUTEXT_HIDE               121
#define IDS_FILTERCOMMAND               122
#define IDS_ERR_GETNEXTWINDOW           123
#define IDS_ERR_QUERYPROCESSINFO        124
#define IDS_NEWREGISTER                 125
#define IDS_PASTE                       126
#define IDS_BUILDDATE                   127
#define IDS_VERSION                     128
#define IDS_NOHOTKEY                    129
#define IDS_NORMALCOMMAND               130
#define IDS_DESCRIPTION_NORMALCOMMAND   131
#define IDR_MAINFRAME                   132
#define IDS_DESCRIPTION_FILTERCOMMAND   132
#define IDS_BUILTINCOMMAND              133
#define IDS_DESCRIPTION_BUILTINCOMMAND  134
#define IDS_GROUPCOMMAND                135
#define IDI_ICON2                       136
#define IDS_ERR_NODELETECOMMAND         136
#define IDS_DESCRIPTION_GROUPCOMMAND    137
#define IDS_ISWAIT                      138
#define IDI_ICON1                       139
#define IDS_ERR_COMMANDDOESNOTEXIST     139
#define IDD_SETTING                     140
#define IDS_ERR_INVALIDSHORTCUT         140
#define IDD_NEWCOMMAND                  141
#define IDS_ERR_INVALIDREGEXP           141
#define IDD_KEYWORDMANAGER              142
#define IDS_ERR_FAILTOSHELLEXECUTE      142
#define IDD_HOTKEY                      143
#define IDS_PATH                        143
#define IDD_SHORTCUT                    144
#define IDS_REGEXPCOMMAND               144
#define IDD_REGISTER_ITEMS              145
#define IDS_DESCRIPTION_REGEXPCOMMAND   145
#define IDD_BASICSETTING                146
#define IDS_ERR_HOTKEYRESERVED          146
#define IDD_EXTENSIONSETTING            147
#define IDS_FILTER_DLL                  147
#define IDD_SHORTCUTSETTING             148
#define IDS_COMMANDTYPE                 148
#define IDD_SELECTCOMMANDTYPE           149
#define IDS_COMMAND_WINDOWACTIVATE      149
#define IDD_GROUP                       150
#define IDS_COMMAND_WORKSHEET           150
#define IDD_FILTEREDIT                  151
#define IDS_COMMAND_BOOKMARK            151
#define IDD_SOYOKAZE_DIALOG1            152
#define IDD_FILTER                      152
#define IDS_COMMAND_BUILTIN             152
#define IDD_EXECSETTING                 153
#define IDS_COMMAND_CALCULATOR          153
#define IDD_INPUTSETTING                154
#define IDS_COMMAND_HISTORY             154
#define IDD_VIEWSETTING                 155
#define IDS_COMMAND_MAILTO              155
#define IDD_REGEXPCOMMAND               156
#define IDS_COMMAND_PATHEXEC            156
#define IDD_SHELLEXECUTECOMMAND2        157
#define IDS_COMMAND_CONTROLPANEL        157
#define IDD_NEWCOMMAND1                 158
#define IDS_COMMAND_PATHEXEC_HISTORY    158
#define IDS_COMMAND_ENVIRON             159
#define IDS_COMMAND_RECENTFILES         160
#define IDS_COMMAND_COLOR               161
#define IDS_COMMAND_VMXFILE             162
#define IDD_ARGUMENTS                   163
#define IDS_ERR_VMXLOCKED               163
#define IDD_SOUNDSETTING                164
#define IDS_FILTER_SOUND                164
#define IDS_COMMANDNAME_WINDOWACTIVATE  165
#define IDD_WINDOWACTIVATEEDIT          165
#define IDS_DESCRIPTION_WINDOWACTIVATE  166
#define IDC_EDIT_COMMAND                1000
#define IDC_STATIC_DESCRIPTION          1001
#define IDC_STATIC_VERSION              1002
#define IDC_EDIT_COMMAND2               1003
#define IDC_STATIC_BUILDDATE            1004
#define IDC_LIST_CANDIDATE              1005
#define IDC_STATIC_ICON                 1006
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_DESCRIPTION            1008
#define IDC_CHECK_RUNASADMIN            1009
#define IDC_EDIT_REPEATS                1010
#define IDC_EDIT_PATTERNSTR             1010
#define IDC_CHECK_USE0                  1011
#define IDC_CHECK_SHOWARGINPUT          1011
#define IDC_BUTTON_BROWSEFILE1          1012
#define IDC_BUTTON_BROWSEDIR1           1013
#define IDC_BUTTON_BROWSEFILE3          1013
#define IDC_BUTTON_BROWSEFILE2          1014
#define IDC_BUTTON_BROWSEDIR4           1014
#define IDC_BUTTON_BROWSEDIR2           1015
#define IDC_STATIC_PATH                 1016
#define IDC_STATIC_PARAM                1017
#define IDC_STATIC_PATH0                1018
#define IDC_STATIC_PATH3                1018
#define IDC_STATIC_PARAM00              1019
#define IDC_STATIC_PATH2                1019
#define IDC_EDIT_PATH                   1020
#define IDC_EDIT_PARAM                  1021
#define IDC_EDIT_HOTKEY                 1022
#define IDC_EDIT_PARAM2                 1022
#define IDC_BUTTON_RESOLVESHORTCUT      1022
#define IDC_EDIT_PATH0                  1023
#define IDC_EDIT_PATH2                  1023
#define IDC_EDIT_PARAM0                 1024
#define IDC_EDIT_SOUNDEXECUTE           1024
#define IDC_EDIT_DIR                    1025
#define IDC_BUTTON_BROWSEDIR3           1026
#define IDC_COMBO_SHOWTYPE              1027
#define IDC_STATIC_STATUSMSG            1028
#define IDC_STATIC_PARAM0               1029
#define IDC_COMBO_AFTERCOMMAND          1029
#define IDC_STATIC_NAME                 1030
#define IDC_BUTTON_RESOLVESHORTCUT2     1030
#define IDC_COMBO_AFTERTYPE             1030
#define IDC_EDIT_HOTKEY2                1031
#define IDC_LIST_COMMANDS               1032
#define IDC_CHECK_USEREGEXP             1032
#define IDC_COMBO_AFTERTYPE2            1032
#define IDC_COMBO_PREFILTERTYPE         1032
#define IDC_BUTTON_NEW                  1033
#define IDC_BUTTON_EDIT                 1034
#define IDC_BUTTON_DOWN                 1036
#define IDC_BUTTON_DELETE               1037
#define IDC_CHECK_USEFILER              1038
#define IDC_BUTTON_UP                   1039
#define IDC_CHECK_ALLOWCONCURRENTEXEC_FILTER 1039
#define IDC_CHECK_TOPMOST               1040
#define IDC_CHECK_SHOWDIR               1040
#define IDC_BUTTON_NEW4                 1041
#define IDC_CHECK_HIDEONINACTIVE        1041
#define IDC_COMBO_TRANSPARENCY          1042
#define IDC_EDIT_ALPHA                  1043
#define IDC_BUTTON_BROWSEFILE           1044
#define IDC_EDIT_DEFAULTCOMMENT         1044
#define IDC_EDIT_FILERPARAM             1045
#define IDC_CHECK_MOVETOCURSOR          1045
#define IDC_BUTTON_HOTKEY               1046
#define IDC_CHECK_SHOWCOMMANDTYPE       1046
#define IDC_EDIT_FILERPATH              1047
#define IDC_BUTTON_SOUNDSELECT          1047
#define IDC_CHECK_SHIFT                 1048
#define IDC_BUTTON_SOUNDEXECUTE         1048
#define IDC_CHECK_USEFILER2             1049
#define IDC_CHECK_SHOWTOGGLE            1050
#define IDC_CHECK_ALT                   1051
#define IDC_CHECK_HIDEONRUN             1052
#define IDC_CHECK_CTRL                  1053
#define IDC_CHECK_IMEOFF                1053
#define IDC_CHECK_WIN                   1054
#define IDC_CHECK_IMEOFF2               1054
#define IDC_CHECK_IGNOREUNC             1054
#define IDC_COMBO_VK                    1055
#define IDC_CHECK_ENABLEMIGEMO          1055
#define IDC_SYSLINK1                    1056
#define IDC_BUTTON_SHORTCUT             1057
#define IDC_SYSLINK2                    1058
#define IDC_CHECK_SENDTO                1059
#define IDC_STATIC_REMARK               1061
#define IDC_CHECK_STARTMENU             1062
#define IDC_LIST_TYPES                  1062
#define IDC_CHECK_DESKTOP               1063
#define IDC_CHECK_PARAM                 1063
#define IDC_CHECK_STARTUP               1064
#define IDC_CHECK_REPEAT                1064
#define IDC_LIST_FILES                  1065
#define IDC_CHECK_CONFIRM               1065
#define IDC_CHECK_RESOLVELINKS          1066
#define IDC_BUTTON_ADD                  1066
#define IDC_TREE_PAGES                  1067
#define IDC_STATIC_BREADCRUMBS          1068
#define IDC_STATIC_AFTERCOMMMAND        1068
#define IDC_STATIC_PAGEAREA             1069
#define IDC_STATIC_AFTERCOMMAND         1069
#define IDC_COMBO_TYPE                  1071
#define IDC_EDIT_ARGUMENTS              1071
#define IDC_EDIT_PYTHONDLLPATH          1071
#define IDC_STATIC_WORKDIR              1072
#define IDC_STATIC_SHOWTYPE             1073
#define IDC_STATIC_PARAMHELP            1074
#define IDC_CHECK_ENABLECALCULATOR      1075
#define IDC_BUTTON_BROWSE               1076
#define IDC_CHECK_ENABLE_WORKSHEET      1077
#define IDC_BUTTON_CLEAR                1077
#define IDC_CHECK_ENABLE_BOOKMARKS      1078
#define IDC_EDIT_SOUNDINPUT             1078
#define IDC_CHECK_ENABLE_WINDOWTITLE    1079
#define IDC_EDIT_SOUNDSELECT            1079
#define IDC_CHECK_ENABLE_CONTROLPANEL   1080
#define IDC_BUTTON_SOUNDINPUT           1080
#define IDC_EDIT_CAPTION                1081
#define IDC_EDIT_CLASS                  1082
#define IDC_CHECK_REGEXP                1083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
