@startuml{filtercommand.svg}

card "前段のプログラム" as precommand

card "標準出力に出力されたテキスト" as preout

actor "利用者" as user

card "絞り込み画面" as filter

card "選択結果\n(1行)" as filteredtext

card "後段のプログラム" as postcommand

precommand -ri-> preout #blue : stdout

preout <-ri- filter #red : もらう

user .do.> filter : 選択操作

filter -ri-> filteredtext #blue : 出力

filteredtext <-ri- postcommand #red : 実行時引数で参照

@enduml

